### ISSUE TITLE
[TASK]: Set Up Development Environment

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#1]
#### Tasks:
- [x] Set up a virtual environment for project dependencies
- [x] Install Django and other required packages (`requirements.txt`)
- [x] Configure local development settings for Django
- [x] Set up development tools (IDE, Git, etc.)
- [x] Set up core structure of the base.html
- [x] Create Home app, index.html, view and URL and ensure it works.
