### ISSUE TITLE
[TASK]: Testing & Validation

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#10]
#### Tasks:
- [x] Ensure and test security of the Full Stack Web application that incorporates Authentication and role-based Authorisation functionality with the following in mind:
   - Implemented login and registration pages that are only available to anonymous users.
   - Implemented functionality that prevents non-admin users from accessing the data store directly without going through the code
   - Apply role-based login and registration functionality
   - Ensure the current login state is reflected to the user
   - Users should not be permitted to access restricted content or functionality before role-based login

<br>

- [x] Create a basic structure for the TESTING.md file
- [x] Regularly update TESTING.md with testing progress

<br>

- [x] Validate all functionalities against user stories
- [x] Manually test all features throughout the site
- [x] Test website design on various devices and screen sizes with AmIResponsive

<br>

- [x] Perform accessibility checks using WAVE Accessibility Tool
- [x] Validate HTML using W3C's services
- [x] Validate CSS using W3C's services
- [x] Validate JavaScript using JSHint
- [x] Conduct Lighthouse audits
- [x] Use CI Python Linter to ensure PEP8 python code standads
- [x] Document all implemented testing in TESTING.md
