### ISSUE TITLE
[TASK]: Final Deployment

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#11]
#### Tasks:

- [x] Ensure that all final deployed code is free of commented out code and has no broken internal links
- [x] Deploy the final version of the application to Heroku
- [x] Test key functionalities in the deployed version
- [x] Fix any deployment-specific issues
- [x] Ensure all features work as expected in the final deployment
- [x] Remove any hardcoded sensitive information
- [x] Configure `DEBUG = False`
- [x] Conduct a final deployment to Heroku
- [x] Document the deployment process in README
