### ISSUE TITLE
[USER STORY]: Easily Find and Read FAQs section

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#14]
### Description:
- **As a Shopper**, I want to be able to **easily identify and read Frequently Asked Questions** so that I can **make sure i understand how everything works**.

### Acceptance Criteria:
- **FAQs Section**: Clearly marked section for news on the homepage/ navigation bar.
- **Easy Access**: Users should be able to access FAQs from a single, dedicated area.

### Tasks:
- [x] Implement a 'FAQs' link in the navbar.
- [x] Ensure the FAQs section are easily accessible and navigable.
- [x] Create a nice page with Frequently Asked Questions
- [x] Implement the Contact Form at the bottom of the page.
