### ISSUE TITLE
[USER STORY]: Easy Account Registration

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#15]
- **As a Site User**, I want the **ability to swiftly create a new realDream account** so that I can **personalize my experience and see my customer profile**.

### Acceptance Criteria:
- **Simple Registration Process**: The user can create an account with minimal steps.
- **Profile Personalization**: After registration, the user can customize their profile.

### Tasks:
- [x] Implement a user registration form with Django's user authentication system.
- [x] Create a user database to store registration information securely.
- [x] Implement a way to easy access the profile after registration, with the option to edit the profile.
