### ISSUE TITLE
[USER STORY]: Update User Profile & Health Status

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#19]
### Description:
- **As a Site User**, I want to **have the option to update/personalize my user profile** so that I can ** update/store shipping and payment information for future use**.

### Acceptance Criteria:
- **Profile Page**: I can access a user profile page or settings where I can edit my profile information.
- **Profile Editing**: Users can edit their profiles with ease.
- **Payment Integration**: Integrate with Stripe to store payment information securely.

### Tasks:
- [x] Create a User Profile model to store additional user information.
- [x] Create a Health Status model to specific health related user information.
- [x] Develop a user profile page or settings where users can edit their information.
- [x] Develop profile editing functionality within the user account settings.
- [x] Set up Stripe to handle and store payment details securely.
