### ISSUE TITLE
[TASK]: Setup Initial SQL- and AWS connection & Heroku Deployment

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#3]
#### Tasks:
- [x] Set up ElephantSQL
- [x] Configure database connection in the Django settings
- [x] Test database connection to ensure proper setup

<br>

- [x] Set up Heroku app and connect to GitHub repository
- [x] Configure environment variables on Heroku (including ElephantSQL URL)
- [x] Perform an initial deployment to test setup

- [x] Set up AWS S3 for image storage and integrate with Django
