### ISSUE TITLE
[TASK]: Design & Aesthetics

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#5]
#### Tasks:

- [x] Decide on a color scheme for the website.
- [x] Create a visually appeling landing page to be displayed before the shop
- [x] Select fonts for headers and text. 
- [x] Create a logo for "realDreams Co."
- [x] Design images and graphics, ensuring they're stored on AWS
- [x] Implement the color palette, theme, and Bootstrap components across the site
- [x] Create a favicon
