### ISSUE TITLE
[USER STORY]: Admin - SEO Enhancing Online Visibility

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#50]
### Description:
**As a Store Owner**, I want **the website to be optimized for search engines (SEO)** so that I can **increase its visibility and attract more organic traffic**.

### Acceptance Criteria:
- Structured website content, optimized for search engine indexing.
- Metadata, including title tags and meta descriptions appropriately optimized for search engines.
- Images and multimedia content have relevant alt text and descriptions.
- Generated sitemap.xml and robots.txt made for search engines for improved crawling and indexing.

### Tasks:
- [x] Ensure that all pages on the site can be reached by a link from another findable page
- [x]  Include Meta Description tags and a site title in the application HTML. Include a site title on the parent template
- [x] Define the relationship between the current document and a linked document:
	- Use “nofollow” for any paid links and distrusted content.
	- Use “sponsored” for any sponsored or compensated links.
- [x] Create a `sitemap.xml` on your application to allow search engine bot crawling
- [x] Include a robots.txt file to control search engine bot crawling
