### ISSUE TITLE
[TASK]: Documentation - Continous Updates

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#52]
#### Tasks:

- [x] Create a basic structure for the README.md file
- [x] Create a basic structure for the TESTING.md file and link to it from README.

<br>

- [x] Regularly update README with project progress
- [x] Ensure clarity and comprehensiveness of documentation
- [x] Ensure all features and functionalities are well-documented
- [x] Conduct a thorough review and spellcheck of all documentation
- [x] Update outdated or incomplete sections
