### ISSUE TITLE
[USER STORY]: Admin - Customize Dream Products dashboard listing

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#53]
### Description:
**As an Admin**, I want **to track when products are added and see a view of customized product information in the listing** so that I can **have a historical context for product listings and manage the catalog more effectively**.

### Acceptance Criteria:
- Each product listing should have a date and time stamp for when it was created.
- These timestamps should be visible and sortable in the admin dashboard.
- Category, price, duration, availability and image are also visible in the product list.

### Tasks:
- [x] Add a `created_at` field to the `Product` model to automatically capture the current date and time when a new product is created.
- [x] Display the `created_at` field in the admin dashboard's product listing.
- [x] Display the rest of the product fields in the admin dashboard's product listing.
- [x] Enable sorting of product listings in the admin dashboard by `created_at`.
