### ISSUE TITLE
[TASK]: Set up Stripe Payments

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#6]
#### Tasks:

- [x] Set up Stripe settings in the account
- [x] Integrate Stripe for payment processing
- [x] Test Stripe integration with dummy transactions
- [x] Implement feedback system (successful or unsuccessful payments) for transactions using Django messages
