### ISSUE TITLE
[TASK]: Create Website Content 

### ISSUE THREAD

**Issue by DebbieBergstrom** [DebbieBergstrom/realDreamsCo#7]
#### Tasks:

- [x] Write content for each page, dream package etc
- [x] Review and edit content for quality and relevance 
- [x] Publish the content on the website
